# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=255)),
                ('dosage_type', models.CharField(max_length=255)),
                ('delivery_method', models.CharField(max_length=255)),
                ('trade_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('drug_strength', models.CharField(max_length=255)),
                ('drug_application_number', models.CharField(max_length=255)),
                ('product_number', models.CharField(max_length=255)),
                ('patent_number', models.CharField(max_length=255)),
                ('approval_date', models.DateField(max_length=255)),
                ('patent_expiration_date', models.DateField(max_length=255)),
            ],
        ),
    ]
